#!/system/bin/sh
#Original Script by jt1134 modified for the vzwtab by KhasMek

mount -o remount,rw /
mount -o remount,rw /dev/block/stl9 /system

cat /res/Superuser.apk > /system/app/Superuser.apk
chmod 0644 /system/app/Superuser.apk
rm /res/Superuser.apk

cat /res/su > /system/xbin/su
chmod 6755 /system/xbin/su
rm /res/su

mount -o remount,ro /
mount -o remount,ro /dev/block/stl9 /system

exit
